name: stroll_test
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons:
  go_router:
  hive_flutter:
  bloc_test:
  mocktail:
  gap:
  flutter_dotenv:
  loading_animation_widget:
  image_picker:
  bottom_sheet:
  smooth_page_indicator:
  cached_network_image:
  pinput:
  permission_handler:
  intl:
  equatable:
  dartz:
  bloc:
  flutter_bloc:
  get_it:
  flutter_gen:
  dartx:
  url_launcher:
  dio:
  flutter_local_notifications:
  firebase_core:
  firebase_messaging:


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  flutter_lints: ^3.0.0

  hive_generator:
  flutter_gen_runner:

flutter:
  uses-material-design: true

  assets:
    - application/assets/images/
    - application/assets/fonts/

